In [2]:
import pandas as pd

In [8]:
crime = pd.read_csv("../합치기/5대범죄현황.csv",thousands=",")
cctv = pd.read_csv("../합치기/cctv.csv",thousands=",")
police = pd.read_csv("../합치기/police_info.csv",thousands=",")
price = pd.read_csv("../합치기/공시지가.csv",thousands=",")
gender = pd.read_csv("../합치기/성비.csv",thousands=",")
single = pd.read_csv("../합치기/여성1인가구.csv",thousands=",")
floating = pd.read_csv("../합치기/유동인구.csv",thousands=",")

den = pd.read_csv("../합치기/인구밀도.csv",thousands=",")

In [65]:
kara = pd.read_csv("../합치기/유흥업소.csv",thousands=",")
kara["지역코드"].replace([111181,111191,111201,111301,111212,111221,111281,111231,111241,111273,111274,111123,111121,111131,111142,111141,111152,111161,111291,111171,111251,111262,111261,111151,111311],["은평구","서대문구","마포구","양천구","강서구","구로구","금천구","영등포구","동작구","송파구","강동구","종로구","중구","용산구","성동구","광진구","동대문구","성북구","강북구","도봉구","관악구","서초구","강남구","중랑구","노원구"], inplace=True)

In [11]:
crime["지역코드"].replace([111181,111191,111201,111301,111212,111221,111281,111231,111241,111273,111274,111123,111121,111131,111142,111141,111152,111161,111291,111171,111251,111262,111261,111151,111311],["은평구","서대문구","마포구","양천구","강서구","구로구","금천구","영등포구","동작구","송파구","강동구","종로구","중구","용산구","성동구","광진구","동대문구","성북구","강북구","도봉구","관악구","서초구","강남구","중랑구","노원구"], inplace=True)
cctv["지역코드"].replace([111181,111191,111201,111301,111212,111221,111281,111231,111241,111273,111274,111123,111121,111131,111142,111141,111152,111161,111291,111171,111251,111262,111261,111151,111311],["은평구","서대문구","마포구","양천구","강서구","구로구","금천구","영등포구","동작구","송파구","강동구","종로구","중구","용산구","성동구","광진구","동대문구","성북구","강북구","도봉구","관악구","서초구","강남구","중랑구","노원구"], inplace=True)
police["지역코드"].replace([111181,111191,111201,111301,111212,111221,111281,111231,111241,111273,111274,111123,111121,111131,111142,111141,111152,111161,111291,111171,111251,111262,111261,111151,111311],["은평구","서대문구","마포구","양천구","강서구","구로구","금천구","영등포구","동작구","송파구","강동구","종로구","중구","용산구","성동구","광진구","동대문구","성북구","강북구","도봉구","관악구","서초구","강남구","중랑구","노원구"], inplace=True)
price["지역코드"].replace([111181,111191,111201,111301,111212,111221,111281,111231,111241,111273,111274,111123,111121,111131,111142,111141,111152,111161,111291,111171,111251,111262,111261,111151,111311],["은평구","서대문구","마포구","양천구","강서구","구로구","금천구","영등포구","동작구","송파구","강동구","종로구","중구","용산구","성동구","광진구","동대문구","성북구","강북구","도봉구","관악구","서초구","강남구","중랑구","노원구"], inplace=True)
gender["지역코드"].replace([111181,111191,111201,111301,111212,111221,111281,111231,111241,111273,111274,111123,111121,111131,111142,111141,111152,111161,111291,111171,111251,111262,111261,111151,111311],["은평구","서대문구","마포구","양천구","강서구","구로구","금천구","영등포구","동작구","송파구","강동구","종로구","중구","용산구","성동구","광진구","동대문구","성북구","강북구","도봉구","관악구","서초구","강남구","중랑구","노원구"], inplace=True)
single["지역코드"].replace([111181,111191,111201,111301,111212,111221,111281,111231,111241,111273,111274,111123,111121,111131,111142,111141,111152,111161,111291,111171,111251,111262,111261,111151,111311],["은평구","서대문구","마포구","양천구","강서구","구로구","금천구","영등포구","동작구","송파구","강동구","종로구","중구","용산구","성동구","광진구","동대문구","성북구","강북구","도봉구","관악구","서초구","강남구","중랑구","노원구"], inplace=True)
floating["지역코드"].replace([111181,111191,111201,111301,111212,111221,111281,111231,111241,111273,111274,111123,111121,111131,111142,111141,111152,111161,111291,111171,111251,111262,111261,111151,111311],["은평구","서대문구","마포구","양천구","강서구","구로구","금천구","영등포구","동작구","송파구","강동구","종로구","중구","용산구","성동구","광진구","동대문구","성북구","강북구","도봉구","관악구","서초구","강남구","중랑구","노원구"], inplace=True)

den["지역코드"].replace([111181,111191,111201,111301,111212,111221,111281,111231,111241,111273,111274,111123,111121,111131,111142,111141,111152,111161,111291,111171,111251,111262,111261,111151,111311],["은평구","서대문구","마포구","양천구","강서구","구로구","금천구","영등포구","동작구","송파구","강동구","종로구","중구","용산구","성동구","광진구","동대문구","성북구","강북구","도봉구","관악구","서초구","강남구","중랑구","노원구"], inplace=True)

    index   지역구  유흥업소개수
0       0   강남구     638
1       1   강동구     286
2       2   강북구     140
3       3   강서구     214
4       4   관악구     401
5       5   광진구      26
6       6   구로구      75
7       7   금천구     101
8       8   노원구      44
9       9   도봉구      31
10     10  동대문구     217
11     11   동작구     101
12     12   마포구     141
13     13  서대문구     101
14     14   서초구     291
15     15   성동구      33
16     16   성북구      24
17     17   송파구     199
18     18   양천구      12
19     19  영등포구     408
20     20   용산구      88
21     21   은평구     134
22     22   종로구     434
23     23    중구     651
24     24   중랑구      46

In [67]:
del cctv["ID"]
del cctv["기간코드"]
del police["ID"]
del police["기간코드"]
del price["ID"]
del price["기간코드"]
del gender["ID"]
del gender["기간코드"]
del gender["남자인구수"]
del gender["여자인구수"]
del single["ID"]
del single["기간코드"]
del single["20세미만"]
del single["20~24세"]
del single["25~29세"]
del single["30~34세"]
del single["35~39세"]
del single["40~44세"]
del single["45~49세"]
del single["50~54세"]
del single["55~59세"]
del single["60~64세"]
del single["65~69세"]
del single["70~74세"]
del single["75~79세"]
del single["80~84세"]
del single["85세이상"]
del floating["ID"]
del floating["기간코드"]
del floating["일최대인구수"]
del floating["일최소인구수"]
del floating["주간인구수"]
del floating["야간인구수"]
del floating["일최대이동인구수"]
del floating["자치구간이동인구수"]
del den["ID"]
del den["기간코드"]
del den["인구"]
del den["면적"]
del kara["ID"]
del kara["기간코드"]
del kara["인허가일자"]

In [85]:
crime.rename(columns={"지역코드":"지역구"},inplace=True)
crime = crime.groupby("지역구").mean()

In [66]:
kara.rename(columns={"지역코드":"지역구"},inplace=True)
kara.rename(columns={"지번주소":"유흥업소개수"},inplace=True)
kara = kara.groupby("지역구").count()
kara

       ID  기간코드  인허가일자  유흥업소개수
지역구
강남구   638   638    638     638
강동구   286   286    286     286
강북구   140   140    140     140
강서구   214   214    214     214
관악구   401   401    401     401
광진구    26    26     26      26
구로구    75    75     75      75
금천구   101   101    101     101
노원구    44    44     44      44
도봉구    31    31     31      31
동대문구  217   217    217     217
동작구   101   101    101     101
마포구   141   141    141     141
서대문구  101   101    101     101
서초구   291   291    291     291
성동구    33    33     33      33
성북구    24    24     24      24
송파구   199   199    199     199
양천구    12    12     12      12
영등포구  408   408    408     408
용산구    88    88     88      88
은평구   134   134    134     134
종로구   434   434    434     434
중구    651   651    651     651
중랑구    46    46     46      46

In [48]:
den = den.groupby("지역코드").mean()
den.reset_index(inplace=True)
den.rename(columns={"지역코드":"지역구"},inplace=True)
den

     지역구    ID  기간코드             인구         면적          인구밀도
0    강남구  47.0  18.0  552904.666667  39.500000  13997.000000
1    강동구  49.0  18.0  437556.333333  24.590000  17794.000000
2    강북구  33.0  18.0  322870.666667  23.600000  13681.000000
3    강서구  40.0  18.0  603379.666667  41.440000  14561.333333
4    관악구  45.0  18.0  519434.333333  29.570000  17566.666667
5    광진구  29.0  18.0  370111.000000  17.060000  21690.666667
6    구로구  41.0  18.0  439805.333333  20.120000  21858.666667
7    금천구  42.0  18.0  253110.666667  13.020000  19440.000000
8    노원구  35.0  18.0  547846.000000  35.440000  15459.333333
9    도봉구  34.0  18.0  341171.333333  20.666667  16509.333333
10  동대문구  30.0  18.0  364457.333333  14.220000  25638.333333
11   동작구  44.0  18.0  408930.000000  16.350000  25004.333333
12   마포구  38.0  18.0  386022.333333  23.850000  16184.333333
13  서대문구  37.0  18.0  323759.666667  17.626667  18368.666667
14   서초구  46.0  18.0  439557.000000  46.983333   9355.666667
15   성동구  28.0  18.0  312717.666667  16.860000  18549.666667
16   성북구  32.0  18.0  452612.666667  24.570000  18418.666667
17   송파구  48.0  18.0  675807.000000  33.870000  19950.666667
18   양천구  39.0  18.0  468482.666667  17.410000  26914.000000
19  영등포구  43.0  18.0  402203.333333  24.550000  16384.000000
20   용산구  27.0  18.0  244906.333333  21.870000  11200.333333
21   은평구  36.0  18.0  487804.666667  29.710000  16419.000000
22   종로구  25.0  18.0  163050.666667  23.910000   6818.333333
23    중구  26.0  18.0  135571.333333   9.960000  13612.000000
24   중랑구  31.0  18.0  407650.333333  18.500000  22040.333333

In [38]:
floating = floating.groupby("지역코드").mean()
floating.reset_index(inplace=True)
floating.rename(columns={"지역코드":"지역구"},inplace=True)
floating

,지역구,ID,기간코드,총생활인구수,일최대인구수,일최소인구수,주간인구수,야간인구수,일최대이동인구수,자치구간이동인구수
0,강남구,25.0,18.5,854191.109984,1.048668e+06,681467.876010,1.007087e+06,744662.330090,618066.450189,300642.333468
1,강동구,41.0,18.5,491665.906874,5.255556e+05,452676.373901,4.625681e+05,512255.179239,229937.516590,47228.517231
2,강북구,23.5,18.5,308292.226003,3.396924e+05,275536.384850,2.827297e+05,326426.414926,146883.949055,46194.578136
3,강서구,21.5,18.5,562166.822869,5.959793e+05,527951.686923,5.364799e+05,580291.129992,259308.963097,64839.843098
4,관악구,35.5,18.5,519260.259695,5.777717e+05,455863.260403,4.700196e+05,554221.338782,223915.101199,63894.460650
5,광진구,29.0,18.5,411229.957027,4.342131e+05,386595.902374,3.953263e+05,422423.287593,197203.642322,71874.053968
6,구로구,26.5,18.5,429923.470033,4.440676e+05,416152.088571,4.241298e+05,433891.348267,216668.948595,73256.552230
7,금천구,25.5,18.5,241324.025339,2.620069e+05,222524.458596,2.572183e+05,229878.373683,152186.028723,50351.171748
8,노원구,1.0,18.5,530086.095316,5.670468e+05,489886.270450,4.987903e+05,552229.946086,232163.481639,63229.626844
9,도봉구,19.0,18.5,292612.685773,3.181905e+05,263451.375855,2.710272e+05,307912.347892,143252.742515,42175.762283
10,동대문구,46.0,18.5,398995.357929,4.076177e+05,389338.217634,3.980557e+05,399508.380061,205697.269255,88656.794814
11,동작구,32.0,18.5,426041.681680,4.559077e+05,392519.283570,4.009417e+05,443800.208668,186219.161913,75027.523636
12,마포구,24.0,18.5,512757.337628,5.541637e+05,472517.106900,5.338089e+05,497514.164426,293331.772505,135344.035263
13,서대문구,14.0,18.5,415056.965509,4.327756e+05,399586.149540,4.235527e+05,408827.844303,226105.607113,107463.042486
14,서초구,29.5,18.5,623070.401557,7.324148e+05,513240.308556,7.108731e+05,560115.510728,434341.690577,203527.444167
15,성동구,31.5,18.5,366028.174662,3.820311e+05,350292.645624,3.737467e+05,360371.501684,205885.861224,97504.144558
16,성북구,43.0,18.5,453646.893769,4.832192e+05,423551.520132,4.307323e+05,469834.946627,197765.405217,79682.545866
17,송파구,22.0,18.5,778700.970572,8.044702e+05,760110.733161,7.824653e+05,775706.477578,408935.418485,122944.607202
18,양천구,13.0,18.5,402087.310578,4.322209e+05,367467.496832,3.765653e+05,420158.067329,191770.651950,63094.683666
19,영등포구,25.5,18.5,523196.276627,5.885530e+05,458518.855642,5.749442e+05,486030.285435,351191.059224,166007.498095
20,용산구,5.0,18.5,327068.807025,3.616852e+05,288601.406118,3.538662e+05,307798.565626,202424.938469,98598.031582
21,은평구,30.0,18.5,450284.102822,4.997878e+05,395210.585480,4.082016e+05,480162.068272,182614.378490,36533.998141
22,종로구,17.5,18.5,348379.361688,4.772121e+05,252291.117117,4.377488e+05,284407.433281,301215.039157,181413.025404
23,중구,19.0,18.5,370891.367146,5.173406e+05,249173.481484,4.802560e+05,292637.184270,333141.286166,209822.246590
24,중랑구,13.0,18.5,366235.599129,4.029823e+05,325166.602534,3.355524e+05,388004.983603,164205.002466,39782.616390

In [100]:
# single = single.groupby("지역코드").mean()
# single.reset_index(inplace=True)
# single.rename(columns={"지역코드":"지역구"},inplace=True)
single.rename(columns={"합계":"여성1인가구합계"},inplace=True)

In [95]:
gender = gender.groupby("지역코드").mean()
gender.reset_index(inplace=True)
gender.rename(columns={"지역코드":"지역구"},inplace=True)
gender

     지역구        남녀성비
0    강남구   91.833333
1    강동구   98.200000
2    강북구   95.666667
3    강서구   94.433333
4    관악구  101.100000
5    광진구   94.566667
6    구로구   98.200000
7    금천구  103.266667
8    노원구   94.233333
9    도봉구   95.933333
10  동대문구   99.466667
11   동작구   94.600000
12   마포구   90.533333
13  서대문구   93.000000
14   서초구   91.833333
15   성동구   96.600000
16   성북구   94.600000
17   송파구   94.266667
18   양천구   97.066667
19  영등포구   99.166667
20   용산구   93.500000
21   은평구   93.766667
22   종로구   95.700000
23    중구   97.166667
24   중랑구   98.833333

In [87]:
cctv.rename(columns={"개수":"cctv개수"},inplace=True)

In [25]:
cctv = cctv.groupby("지역코드").mean()
cctv.reset_index(inplace=True)
cctv.rename(columns={"지역코드":"지역구"},inplace=True)
police = police.groupby("지역코드").mean()
police.reset_index(inplace=True)
police.rename(columns={"지역코드":"지역구","sum(경찰관수)":"경찰관수","sum(total)":"파출소개수"},inplace=True)

In [30]:
price = price.groupby("지역코드").mean()
price.reset_index(inplace=True)
price.rename(columns={"지역코드":"지역구"},inplace=True)

     지역구  ID  기간코드          평균지가
0    강남구   1    18  8.362000e+06
1    강동구   4    18  4.539267e+06
2    강북구   7    18  2.118367e+06
3    강서구  10    18  2.452213e+06
4    관악구  13    18  1.571440e+06
5    광진구  16    18  2.596233e+06
6    구로구  19    18  3.149733e+06
7    금천구  22    18  2.185560e+06
8    노원구  25    18  1.233500e+06
9    도봉구  28    18  1.431373e+06
10  동대문구  31    18  2.961200e+06
11   동작구  34    18  3.751867e+06
12   마포구  37    18  4.147933e+06
13  서대문구  40    18  5.484527e+06
14   서초구  43    18  5.125127e+06
15   성동구  46    18  4.918400e+06
16   성북구  49    18  2.806593e+06
17   송파구  52    18  4.911067e+06
18   양천구  55    18  2.575647e+06
19  영등포구  58    18  2.202013e+06
20   용산구  61    18  3.864653e+06
21   은평구  64    18  2.714113e+06
22   종로구  67    18  2.530773e+06
23    중구  70    18  1.785933e+07
24   중랑구  73    18  1.308680e+06

,ID_x,기간코드_x,지역코드,합계,살인,강도,강간강제추행,절도,폭력,ID_y,기간코드_y,개수
0,0,17,강남구,7720,7,20,607,3130,3956,25.0,18.0,845.333333
1,25,18,강남구,7513,10,14,600,3004,3885,25.0,18.0,845.333333
2,50,19,강남구,7304,5,5,666,2970,3658,25.0,18.0,845.333333
3,1,17,영등포구,5969,15,5,455,2304,3190,30.0,18.0,344.666667
4,26,18,영등포구,5840,17,8,391,2292,3132,30.0,18.0,344.666667
...,...,...,...,...,...,...,...,...,...,...,...,...
70,48,18,성동구,2457,2,5,126,999,1325,32.0,18.0,508.666667
71,73,19,성동구,2512,6,9,133,970,1394,32.0,18.0,508.666667
72,24,17,도봉구,1999,1,3,104,633,1258,49.0,18.0,184.666667
73,49,18,도봉구,2249,1,5,113,781,1349,49.0,18.0,184.666667
74,74,19,도봉구,2110,1,5,90,790,1224,49.0,18.0,184.666667

In [105]:
a = crime.merge(cctv,on="지역구")
b = a.merge(police,on="지역구")
c = b.merge(price,on="지역구")
d = c.merge(gender,on="지역구")
e = d.merge(single,on="지역구")
f = e.merge(floating,on="지역구")
g = f.merge(den,on="지역구")
final = g.merge(kara,on="지역구")

In [107]:
del final["ID"]
del final["index_x"]
del final["index_y"]

In [110]:

final.to_csv("csv합침.csv",sep=",",na_rep="")