In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 전체 코드 출력
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [33]:
# 한글 문제
# matplotlit의 기본 폰트에서 한글 지원되지 않기 때문에
# matplotlib의 폰트 변경 필요
import platform

from matplotlib import font_manager, rc
plt.rcParams['axes.unicode_minus'] = False

if platform.system() == 'Darwin':  # 맥OS 
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows':  # 윈도우
    path = "c:/Windows/Fonts/malgun.ttf"
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    print('Unknown system...  sorry~~~')

In [34]:
single_house = pd.read_excel('../[0]data/서울시_1인가구_연령별.xls')
single_house

,기간,구분,성별,합계,20세미만,20~24세,25~29세,30~34세,35~39세,40~44세,45~49세,50~54세,55~59세,60~64세,65~69세,70~74세,75~79세,80~84세,85세이상
0,2017,합계,계,1180540,14190,103451,179568,152797,112945,87540,87497,73980,83472,75860,61577,52768,47620,29344,17931
1,2017,합계,남자,561524,5769,38633,90451,85828,63595,50156,51922,43351,42590,32292,22070,14973,11185,5553,3156
2,2017,합계,여자,619016,8421,64818,89117,66969,49350,37384,35575,30629,40882,43568,39507,37795,36435,23791,14775
3,2017,종로구,계,23638,507,2992,3627,2552,1796,1518,1723,1540,1660,1471,1151,1065,998,608,430
4,2017,종로구,남자,11594,191,1138,2082,1374,967,824,982,931,947,756,502,372,287,146,95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,2019,송파구,남자,31036,136,978,4623,5697,4352,2954,2958,2301,2119,1834,1176,872,554,296,186
230,2019,송파구,여자,37825,146,1928,6131,5328,4244,2719,2348,1843,2265,2829,2272,2090,1628,1138,916
231,2019,강동구,계,45188,157,1859,5687,5270,4403,3306,3631,3332,3886,4134,3042,2500,1876,1276,829
232,2019,강동구,남자,21674,68,598,2582,2940,2492,1877,2192,2025,2130,1823,1174,833,508,279,153
233,2019,강동구,여자,23514,89,1261,3105,2330,1911,1429,1439,1307,1756,2311,1868,1667,1368,997,676

In [35]:
single_house=single_house.iloc[2::3]
single_house

,기간,구분,성별,합계,20세미만,20~24세,25~29세,30~34세,35~39세,40~44세,45~49세,50~54세,55~59세,60~64세,65~69세,70~74세,75~79세,80~84세,85세이상
2,2017,합계,여자,619016,8421,64818,89117,66969,49350,37384,35575,30629,40882,43568,39507,37795,36435,23791,14775
5,2017,종로구,여자,12044,316,1854,1545,1178,829,694,741,609,713,715,649,693,711,462,335
8,2017,중구,여자,10338,350,1302,1250,934,770,615,641,536,669,659,632,603,694,405,278
11,2017,용산구,여자,17900,196,2116,2485,1989,1620,1198,1195,855,1012,985,928,985,1024,785,527
14,2017,성동구,여자,19103,387,2415,2733,1924,1469,1211,1134,910,1157,1216,1125,1128,1159,717,418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221,2019,관악구,여자,57263,557,9296,15689,7730,4151,2363,2087,1778,2131,2638,2273,2319,2118,1353,780
224,2019,서초구,여자,23875,294,1699,3608,3401,2663,1812,1702,1244,1226,1556,1282,1191,979,662,556
227,2019,강남구,여자,37886,331,2306,6161,6162,4935,3098,2363,1685,1650,2188,1926,1762,1408,1016,895
230,2019,송파구,여자,37825,146,1928,6131,5328,4244,2719,2348,1843,2265,2829,2272,2090,1628,1138,916
233,2019,강동구,여자,23514,89,1261,3105,2330,1911,1429,1439,1307,1756,2311,1868,1667,1368,997,676

In [36]:
single_house.head(30)
single_house.tail(30)

,기간,구분,성별,합계,20세미만,20~24세,25~29세,30~34세,35~39세,40~44세,45~49세,50~54세,55~59세,60~64세,65~69세,70~74세,75~79세,80~84세,85세이상
2,2017,합계,여자,619016,8421,64818,89117,66969,49350,37384,35575,30629,40882,43568,39507,37795,36435,23791,14775
5,2017,종로구,여자,12044,316,1854,1545,1178,829,694,741,609,713,715,649,693,711,462,335
8,2017,중구,여자,10338,350,1302,1250,934,770,615,641,536,669,659,632,603,694,405,278
11,2017,용산구,여자,17900,196,2116,2485,1989,1620,1198,1195,855,1012,985,928,985,1024,785,527
14,2017,성동구,여자,19103,387,2415,2733,1924,1469,1211,1134,910,1157,1216,1125,1128,1159,717,418
17,2017,광진구,여자,28236,453,3885,5203,3667,2491,1659,1537,1307,1619,1651,1286,1174,1145,707,452
20,2017,동대문구,여자,26392,976,5103,3486,2077,1547,1181,1177,1075,1515,1668,1654,1696,1658,1002,577
23,2017,중랑구,여자,23543,115,1209,2217,1954,1649,1454,1596,1674,2253,2213,1975,1866,1727,1004,637
26,2017,성북구,여자,29683,977,6225,3778,2157,1574,1355,1444,1247,1660,1874,1740,1874,1845,1207,726
29,2017,강북구,여자,21273,262,1616,1787,1355,1206,1147,1348,1327,1873,1960,1998,1923,1835,1043,593
32,2017,도봉구,여자,16376,170,1016,982,871,892,931,1120,1024,1570,1617,1479,1463,1557,1057,627
35,2017,노원구,여자,28525,682,3028,1696,1326,1378,1419,1601,1534,2297,2743,2651,2608,2681,1794,1087
38,2017,은평구,여자,25808,108,1301,2482,2276,1999,1709,1716,1530,2163,2322,2120,2169,2063,1213,637
41,2017,서대문구,여자,24527,545,5157,3814,2017,1432,1141,1195,933,1227,1368,1277,1389,1513,994,525
44,2017,마포구,여자,30126,367,3618,5474,4358,2973,2128,1710,1200,1324,1397,1373,1386,1357,938,523
47,2017,양천구,여자,17836,71,623,1382,1357,1239,1181,1249,1170,1670,1831,1580,1417,1386,1009,671
50,2017,강서구,여자,36703,156,2512,5753,4320,3146,2234,2030,1850,2710,2924,2444,2194,2017,1422,991
53,2017,구로구,여자,21618,103,1423,3034,2252,1672,1327,1245,1149,1663,1775,1552,1501,1445,957,520
56,2017,금천구,여자,14623,55,873,1859,1314,928,819,966,1026,1315,1333,1163,1025,1014,598,335
59,2017,영등포구,여자,25198,112,1902,4667,3320,2037,1540,1360,1247,1544,1553,1495,1398,1403,1034,586
62,2017,동작구,여자,27966,618,3928,5061,3343,2023,1444,1293,1074,1477,1621,1627,1523,1453,934,547
65,2017,관악구,여자,49787,556,7359,12378,7023,3921,2354,1981,1728,2269,2410,2158,2052,1917,1050,631
68,2017,서초구,여자,22219,335,1636,3360,3188,2430,1815,1543,1092,1253,1406,1163,1056,857,617,468
71,2017,강남구,여자,36259,279,2188,5814,6138,4803,3016,2229,1614,1786,2014,1823,1565,1321,920,749
74,2017,송파구,여자,31947,141,1540,4504,4559,3562,2447,2163,1652,2242,2316,1922,1696,1394,1064,745
77,2017,강동구,여자,20986,91,989,2373,2072,1760,1365,1361,1266,1901,1997,1693,1411,1259,858,590
80,2018,합계,여자,647477,8858,69397,97492,68705,51906,36617,36662,31094,40141,46827,40580,39737,37701,25619,16141
83,2018,종로구,여자,12691,494,1980,1748,1146,904,676,770,670,711,707,619,702,707,509,348
86,2018,중구,여자,10751,405,1365,1346,1027,801,607,625,543,659,678,634,603,681,467,310
89,2018,용산구,여자,18446,247,2137,2668,2096,1724,1195,1204,864,944,1057,891,994,1015,836,574

,기간,구분,성별,합계,20세미만,20~24세,25~29세,30~34세,35~39세,40~44세,45~49세,50~54세,55~59세,60~64세,65~69세,70~74세,75~79세,80~84세,85세이상
146,2018,서초구,여자,23055,294,1661,3459,3218,2662,1777,1650,1197,1254,1469,1238,1125,930,635,486
149,2018,강남구,여자,36009,243,2176,5833,5922,4868,2917,2201,1579,1631,2039,1823,1631,1355,978,813
152,2018,송파구,여자,34711,127,1784,5282,4904,3958,2501,2290,1721,2223,2626,2109,1806,1470,1090,820
155,2018,강동구,여자,21722,80,1091,2588,2139,1774,1357,1399,1210,1898,2145,1728,1530,1276,885,622
158,2019,합계,여자,688226,7796,75329,110089,73779,53658,37572,37595,32448,39430,49881,42516,42572,39261,28060,18240
161,2019,종로구,여자,12729,349,2044,1725,1181,913,678,760,641,725,755,639,704,727,534,354
164,2019,중구,여자,11401,325,1444,1482,1158,874,662,648,578,646,752,634,658,678,494,368
167,2019,용산구,여자,18944,192,2119,2817,2238,1801,1231,1205,918,917,1083,925,1012,1025,873,588
170,2019,성동구,여자,20963,347,2693,3182,2132,1623,1186,1268,983,1177,1331,1199,1242,1210,884,506
173,2019,광진구,여자,30679,364,4281,6075,3974,2669,1637,1548,1352,1612,1822,1401,1300,1221,849,574
176,2019,동대문구,여자,28976,941,6199,4063,2149,1582,1223,1230,1109,1450,1884,1672,1795,1774,1204,701
179,2019,중랑구,여자,26208,111,1342,2937,2218,1769,1380,1583,1701,2266,2708,2143,2123,1886,1248,793
182,2019,성북구,여자,31701,908,6855,4257,2197,1631,1272,1523,1271,1632,2061,1796,2033,1933,1427,905
185,2019,강북구,여자,23274,224,2120,2207,1400,1201,1065,1349,1431,1788,2275,2067,2155,2039,1261,692
188,2019,도봉구,여자,18257,110,1141,1294,972,970,901,1174,1162,1514,1968,1617,1670,1683,1262,819
191,2019,노원구,여자,30809,420,3088,2023,1393,1464,1360,1666,1722,2246,3125,2868,2980,2926,2131,1397
194,2019,은평구,여자,29605,137,1737,3603,2617,2264,1701,1857,1606,2109,2735,2319,2341,2204,1521,854
197,2019,서대문구,여자,26288,530,5587,4166,2096,1524,1138,1231,1044,1219,1558,1355,1472,1507,1182,679
200,2019,마포구,여자,33577,298,4335,6696,4721,3264,2153,1928,1305,1303,1547,1327,1525,1450,1070,655
203,2019,양천구,여자,19687,77,778,1729,1498,1308,1145,1258,1171,1545,2097,1823,1734,1537,1176,811
206,2019,강서구,여자,43142,192,3037,7963,5221,3472,2423,2249,1989,2590,3479,2803,2582,2236,1701,1205
209,2019,구로구,여자,24285,126,1785,3824,2485,1731,1249,1359,1200,1582,2040,1763,1767,1541,1165,668
212,2019,금천구,여자,17079,83,1237,2762,1622,1081,803,995,1033,1302,1506,1280,1143,1122,703,407
215,2019,영등포구,여자,28917,139,2338,6251,3999,2403,1547,1482,1176,1433,1759,1522,1524,1519,1090,735
218,2019,동작구,여자,31342,506,4679,6339,3557,2210,1397,1343,1199,1346,1874,1742,1783,1542,1119,706
221,2019,관악구,여자,57263,557,9296,15689,7730,4151,2363,2087,1778,2131,2638,2273,2319,2118,1353,780
224,2019,서초구,여자,23875,294,1699,3608,3401,2663,1812,1702,1244,1226,1556,1282,1191,979,662,556
227,2019,강남구,여자,37886,331,2306,6161,6162,4935,3098,2363,1685,1650,2188,1926,1762,1408,1016,895
230,2019,송파구,여자,37825,146,1928,6131,5328,4244,2719,2348,1843,2265,2829,2272,2090,1628,1138,916
233,2019,강동구,여자,23514,89,1261,3105,2330,1911,1429,1439,1307,1756,2311,1868,1667,1368,997,676

In [37]:
single_house=single_house.drop(index=[2,80,158])

In [38]:
single_house.rename(columns={ single_house.columns[1]:"지역구"},inplace=True)

In [39]:
single_house=single_house.set_index(['기간','지역구'])

In [40]:
single_house = single_house.drop(columns='성별')

In [41]:
single_house.head(10)
single_house.tail(10)

              합계  20세미만  20~24세  25~29세  30~34세  35~39세  40~44세  45~49세  \
기간   지역구
2017 종로구   12044    316    1854    1545    1178     829     694     741
     중구    10338    350    1302    1250     934     770     615     641
     용산구   17900    196    2116    2485    1989    1620    1198    1195
     성동구   19103    387    2415    2733    1924    1469    1211    1134
     광진구   28236    453    3885    5203    3667    2491    1659    1537
     동대문구  26392    976    5103    3486    2077    1547    1181    1177
     중랑구   23543    115    1209    2217    1954    1649    1454    1596
     성북구   29683    977    6225    3778    2157    1574    1355    1444
     강북구   21273    262    1616    1787    1355    1206    1147    1348
     도봉구   16376    170    1016     982     871     892     931    1120

           50~54세  55~59세  60~64세  65~69세  70~74세  75~79세  80~84세  85세이상
기간   지역구
2017 종로구      609     713     715     649     693     711     462    335
     중구       536     669     659     632     603     694     405    278
     용산구      855    1012     985     928     985    1024     785    527
     성동구      910    1157    1216    1125    1128    1159     717    418
     광진구     1307    1619    1651    1286    1174    1145     707    452
     동대문구    1075    1515    1668    1654    1696    1658    1002    577
     중랑구     1674    2253    2213    1975    1866    1727    1004    637
     성북구     1247    1660    1874    1740    1874    1845    1207    726
     강북구     1327    1873    1960    1998    1923    1835    1043    593
     도봉구     1024    1570    1617    1479    1463    1557    1057    627

              합계  20세미만  20~24세  25~29세  30~34세  35~39세  40~44세  45~49세  \
기간   지역구
2019 강서구   43142    192    3037    7963    5221    3472    2423    2249
     구로구   24285    126    1785    3824    2485    1731    1249    1359
     금천구   17079     83    1237    2762    1622    1081     803     995
     영등포구  28917    139    2338    6251    3999    2403    1547    1482
     동작구   31342    506    4679    6339    3557    2210    1397    1343
     관악구   57263    557    9296   15689    7730    4151    2363    2087
     서초구   23875    294    1699    3608    3401    2663    1812    1702
     강남구   37886    331    2306    6161    6162    4935    3098    2363
     송파구   37825    146    1928    6131    5328    4244    2719    2348
     강동구   23514     89    1261    3105    2330    1911    1429    1439

           50~54세  55~59세  60~64세  65~69세  70~74세  75~79세  80~84세  85세이상
기간   지역구
2019 강서구     1989    2590    3479    2803    2582    2236    1701   1205
     구로구     1200    1582    2040    1763    1767    1541    1165    668
     금천구     1033    1302    1506    1280    1143    1122     703    407
     영등포구    1176    1433    1759    1522    1524    1519    1090    735
     동작구     1199    1346    1874    1742    1783    1542    1119    706
     관악구     1778    2131    2638    2273    2319    2118    1353    780
     서초구     1244    1226    1556    1282    1191     979     662    556
     강남구     1685    1650    2188    1926    1762    1408    1016    895
     송파구     1843    2265    2829    2272    2090    1628    1138    916
     강동구     1307    1756    2311    1868    1667    1368     997    676

In [42]:
single_house.to_csv('../[0]data/서울시_1인가구_여자_연령별(결과).csv')