In [32]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt

# 전체 코드 출력
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [33]:
# 한글 문제
# matplotlit의 기본 폰트에서 한글 지원되지 않기 때문에
# matplotlib의 폰트 변경 필요
import platform

from matplotlib import font_manager, rc
plt.rcParams['axes.unicode_minus'] = False

if platform.system() == 'Darwin':  # 맥OS 
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows':  # 윈도우
    path = "c:/Windows/Fonts/malgun.ttf"
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    print('Unknown system...  sorry~~~')

In [34]:
crime_data = pd.read_excel('../[0]data/서울시_5대범죄_년도별.xls')
crime_data

,기간,자치구,합계,합계.1,살인,살인.1,강도,강도.1,강간강제추행,강간강제추행.1,절도,절도.1,폭력,폭력.1
0,기간,자치구,발생,검거,발생,검거,발생,검거,발생,검거,발생,검거,발생,검거
1,2017,합계,107835,79865,142,140,169,170,6963,6558,41162,21421,59399,51576
2,2017,종로구,4057,4437,7,9,10,15,253,1412,1644,905,2143,2096
3,2017,중구,4184,2851,1,-,9,9,267,149,1846,889,2061,1804
4,2017,용산구,4060,2936,1,1,5,4,327,289,1346,626,2381,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,2019,관악구,5328,3810,13,10,10,11,408,335,2223,1085,2674,2369
75,2019,서초구,5542,3750,5,5,7,5,616,412,2270,1118,2644,2210
76,2019,강남구,7304,5069,5,3,5,6,666,562,2970,1339,3658,3159
77,2019,송파구,5698,3799,7,8,10,10,273,230,2416,1016,2992,2535
78,2019,강동구,4014,2955,6,5,15,14,180,155,1650,907,2163,1874

In [35]:
crime_data_new= crime_data.iloc[:,4::2]
crime_data_new

     살인   강도 강간강제추행     절도     폭력
0    발생   발생     발생     발생     발생
1   142  169   6963  41162  59399
2     7   10    253   1644   2143
3     1    9    267   1846   2061
4     1    5    327   1346   2381
..  ...  ...    ...    ...    ...
74   13   10    408   2223   2674
75    5    7    616   2270   2644
76    5    5    666   2970   3658
77    7   10    273   2416   2992
78    6   15    180   1650   2163

[79 rows x 5 columns]

In [36]:
crime_data_name = crime_data.iloc[:,0:2]
crime_data_name

      기간  자치구
0     기간  자치구
1   2017   합계
2   2017  종로구
3   2017   중구
4   2017  용산구
..   ...  ...
74  2019  관악구
75  2019  서초구
76  2019  강남구
77  2019  송파구
78  2019  강동구

[79 rows x 2 columns]

In [37]:
crime_data = pd.concat([crime_data_name,crime_data_new],axis=1)
crime_data.head(30)
crime_data.tail(30)

      기간   자치구   살인   강도 강간강제추행     절도     폭력
0     기간   자치구   발생   발생     발생     발생     발생
1   2017    합계  142  169   6963  41162  59399
2   2017   종로구    7   10    253   1644   2143
3   2017    중구    1    9    267   1846   2061
4   2017   용산구    1    5    327   1346   2381
5   2017   성동구    1    3    132   1072   1559
6   2017   광진구    6   13    261   2220   2146
7   2017  동대문구   11    3    165   1547   2249
8   2017   중랑구    5    3    172   1533   2858
9   2017   성북구    7    8    173   1344   1902
10  2017   강북구    8    7    208   1014   2156
11  2017   도봉구    1    3    104    633   1258
12  2017   노원구    4    9    180   1538   2478
13  2017   은평구    6    4    230   1387   2256
14  2017  서대문구    4    1    202   1230   1676
15  2017   마포구    3    8    500   2094   2673
16  2017   양천구    3    3    138   1590   2148
17  2017   강서구   11    4    316   1888   2916
18  2017   구로구    7    8    328   1725   2827
19  2017   금천구    5    5    240   1141   1874
20  2017  영등포구   15    5    455   2304   3190
21  2017   동작구    1    7    396   1226   1700
22  2017   관악구    8    7    379   1979   3152
23  2017   서초구    9   13    470   1812   2404
24  2017   강남구    7   20    607   3130   3956
25  2017   송파구    6    1    288   2274   3007
26  2017   강동구    5   10    172   1645   2429
27  2018    합계  143  143   6412  39175  56075
28  2018   종로구    6    3    236   1483   1962
29  2018    중구    2   11    207   1855   1955

      기간   자치구   살인   강도 강간강제추행     절도     폭력
49  2018   서초구    5    5    470   1851   2395
50  2018   강남구   10   14    600   3004   3885
51  2018   송파구    5    6    309   2352   3135
52  2018   강동구    3    7    170   1515   2224
53  2019    합계  136  136   6469  42204  54723
54  2019   종로구    4    7    238   1515   2082
55  2019    중구    2    6    195   2202   1922
56  2019   용산구    3    3    272    999   2036
57  2019   성동구    6    9    133    970   1394
58  2019   광진구    4    6    273   1875   1853
59  2019  동대문구    6   10    168   1531   1977
60  2019   중랑구   10    4    138   1666   2450
61  2019   성북구    3    3    176   1082   1613
62  2019   강북구    6    3    176   1229   2424
63  2019   도봉구    1    5     90    790   1224
64  2019   노원구    4    3    184   1498   2464
65  2019   은평구    3    1    194   1565   2117
66  2019  서대문구    2    5    175   1226   1535
67  2019   마포구    2    2    495   2190   2153
68  2019   양천구    6    2    127   1477   1602
69  2019   강서구    8    3    306   2050   2557
70  2019   구로구   10    3    226   1916   2552
71  2019   금천구    6   10    153   1157   1779
72  2019  영등포구   10    3    356   2409   3042
73  2019   동작구    4    1    251   1328   1816
74  2019   관악구   13   10    408   2223   2674
75  2019   서초구    5    7    616   2270   2644
76  2019   강남구    5    5    666   2970   3658
77  2019   송파구    7   10    273   2416   2992
78  2019   강동구    6   15    180   1650   2163

In [38]:
 crime_data.drop(index=[0,1,27,53],inplace=True)

In [39]:
crime_data.head(30)
crime_data.tail(30)

      기간   자치구  살인  강도 강간강제추행    절도    폭력
2   2017   종로구   7  10    253  1644  2143
3   2017    중구   1   9    267  1846  2061
4   2017   용산구   1   5    327  1346  2381
5   2017   성동구   1   3    132  1072  1559
6   2017   광진구   6  13    261  2220  2146
7   2017  동대문구  11   3    165  1547  2249
8   2017   중랑구   5   3    172  1533  2858
9   2017   성북구   7   8    173  1344  1902
10  2017   강북구   8   7    208  1014  2156
11  2017   도봉구   1   3    104   633  1258
12  2017   노원구   4   9    180  1538  2478
13  2017   은평구   6   4    230  1387  2256
14  2017  서대문구   4   1    202  1230  1676
15  2017   마포구   3   8    500  2094  2673
16  2017   양천구   3   3    138  1590  2148
17  2017   강서구  11   4    316  1888  2916
18  2017   구로구   7   8    328  1725  2827
19  2017   금천구   5   5    240  1141  1874
20  2017  영등포구  15   5    455  2304  3190
21  2017   동작구   1   7    396  1226  1700
22  2017   관악구   8   7    379  1979  3152
23  2017   서초구   9  13    470  1812  2404
24  2017   강남구   7  20    607  3130  3956
25  2017   송파구   6   1    288  2274  3007
26  2017   강동구   5  10    172  1645  2429
28  2018   종로구   6   3    236  1483  1962
29  2018    중구   2  11    207  1855  1955
30  2018   용산구   1   3    331  1096  1980
31  2018   성동구   2   5    126   999  1325
32  2018   광진구   7   2    229  1769  1908

      기간   자치구  살인  강도 강간강제추행    절도    폭력
48  2018   관악구   9  10    352  2012  2643
49  2018   서초구   5   5    470  1851  2395
50  2018   강남구  10  14    600  3004  3885
51  2018   송파구   5   6    309  2352  3135
52  2018   강동구   3   7    170  1515  2224
54  2019   종로구   4   7    238  1515  2082
55  2019    중구   2   6    195  2202  1922
56  2019   용산구   3   3    272   999  2036
57  2019   성동구   6   9    133   970  1394
58  2019   광진구   4   6    273  1875  1853
59  2019  동대문구   6  10    168  1531  1977
60  2019   중랑구  10   4    138  1666  2450
61  2019   성북구   3   3    176  1082  1613
62  2019   강북구   6   3    176  1229  2424
63  2019   도봉구   1   5     90   790  1224
64  2019   노원구   4   3    184  1498  2464
65  2019   은평구   3   1    194  1565  2117
66  2019  서대문구   2   5    175  1226  1535
67  2019   마포구   2   2    495  2190  2153
68  2019   양천구   6   2    127  1477  1602
69  2019   강서구   8   3    306  2050  2557
70  2019   구로구  10   3    226  1916  2552
71  2019   금천구   6  10    153  1157  1779
72  2019  영등포구  10   3    356  2409  3042
73  2019   동작구   4   1    251  1328  1816
74  2019   관악구  13  10    408  2223  2674
75  2019   서초구   5   7    616  2270  2644
76  2019   강남구   5   5    666  2970  3658
77  2019   송파구   7  10    273  2416  2992
78  2019   강동구   6  15    180  1650  2163

In [40]:
 crime_data.rename(columns={ crime_data.columns[1]:"지역구"},inplace=True)

In [41]:
crime_data=crime_data.set_index(["기간","지역구"])

In [42]:
col=["살인","강도","강간강제추행","절도","폭력"]
crime_data["5대범죄"] = np.sum(crime_data[col],axis=1)

In [43]:
crime_data.head(25)

           살인  강도 강간강제추행    절도    폭력    5대범죄
기간   지역구
2017 종로구    7  10    253  1644  2143  4057.0
     중구     1   9    267  1846  2061  4184.0
     용산구    1   5    327  1346  2381  4060.0
     성동구    1   3    132  1072  1559  2767.0
     광진구    6  13    261  2220  2146  4646.0
     동대문구  11   3    165  1547  2249  3975.0
     중랑구    5   3    172  1533  2858  4571.0
     성북구    7   8    173  1344  1902  3434.0
     강북구    8   7    208  1014  2156  3393.0
     도봉구    1   3    104   633  1258  1999.0
     노원구    4   9    180  1538  2478  4209.0
     은평구    6   4    230  1387  2256  3883.0
     서대문구   4   1    202  1230  1676  3113.0
     마포구    3   8    500  2094  2673  5278.0
     양천구    3   3    138  1590  2148  3882.0
     강서구   11   4    316  1888  2916  5135.0
     구로구    7   8    328  1725  2827  4895.0
     금천구    5   5    240  1141  1874  3265.0
     영등포구  15   5    455  2304  3190  5969.0
     동작구    1   7    396  1226  1700  3330.0
     관악구    8   7    379  1979  3152  5525.0
     서초구    9  13    470  1812  2404  4708.0
     강남구    7  20    607  3130  3956  7720.0
     송파구    6   1    288  2274  3007  5576.0
     강동구    5  10    172  1645  2429  4261.0

In [44]:
crime_data.head(5)
crime_data.tail(5)

         살인  강도 강간강제추행    절도    폭력    5대범죄
기간   지역구
2017 종로구  7  10    253  1644  2143  4057.0
     중구   1   9    267  1846  2061  4184.0
     용산구  1   5    327  1346  2381  4060.0
     성동구  1   3    132  1072  1559  2767.0
     광진구  6  13    261  2220  2146  4646.0

          살인  강도 강간강제추행    절도    폭력    5대범죄
기간   지역구
2019 관악구  13  10    408  2223  2674  5328.0
     서초구   5   7    616  2270  2644  5542.0
     강남구   5   5    666  2970  3658  7304.0
     송파구   7  10    273  2416  2992  5698.0
     강동구   6  15    180  1650  2163  4014.0

In [45]:
crime_data.to_csv('../[0]data/서울시_5대범죄율_발생건수(결과).csv')