In [348]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 전체 코드 출력
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [349]:
# 한글 문제
# matplotlit의 기본 폰트에서 한글 지원되지 않기 때문에
# matplotlib의 폰트 변경 필요
import platform

from matplotlib import font_manager, rc
plt.rcParams['axes.unicode_minus'] = False

if platform.system() == 'Darwin':  # 맥OS 
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows':  # 윈도우
    path = "c:/Windows/Fonts/malgun.ttf"
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    print('Unknown system...  sorry~~~')

In [350]:
CCTV = pd.read_csv('../[0]data/서울시_CCTV_년도별.csv',encoding='euc-kr',header=1,thousands=',')
CCTV

,구분,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
0,계,77032,7667,2200,3491,4439,6582,8129,9947,9876,11961,11132,1608
1,종로구,1772,813,0,0,210,150,1,261,85,9,200,43
2,중 구,2333,16,114,87,77,236,240,372,386,155,361,289
3,용산구,2383,34,71,234,125,221,298,351,125,307,617,0
4,성동구,3602,448,125,212,105,339,310,874,390,262,461,76
5,광진구,2588,35,57,100,187,98,52,675,465,712,175,32
6,동대문구,2497,1090,146,60,29,111,233,136,197,209,223,63
7,중랑구,3296,302,24,253,88,141,161,162,173,1049,939,4
8,성북구,3958,83,78,170,230,323,594,460,867,714,251,188
9,강북구,2462,0,0,24,65,105,243,6,392,1000,588,39
10,도봉구,1629,39,22,96,181,79,159,134,222,198,168,331
11,노원구,2415,0,97,193,77,516,331,175,216,320,386,104
12,은평구,3791,14,3,44,332,329,555,403,635,1057,288,131
13,서대문구,2940,730,253,155,108,137,223,356,237,343,397,1
14,마포구,2421,58,93,77,61,162,454,359,343,494,300,20
15,양천구,3312,1413,167,181,143,180,350,139,140,274,325,0
16,강서구,2560,55,129,106,213,188,168,506,259,457,356,123
17,구로구,4075,852,216,349,187,268,326,540,488,434,415,0
18,금천구,2374,0,0,178,80,361,133,196,540,369,508,9
19,영등포구,3778,572,136,238,123,209,248,311,658,65,1213,5
20,동작구,2297,41,24,25,503,128,253,271,300,322,419,11
21,관악구,4942,428,205,291,513,529,621,687,663,640,331,34
22,서초구,3704,116,75,94,71,563,516,1060,428,358,420,3
23,강남구,6502,124,77,75,597,840,1310,999,748,789,942,1
24,송파구,2854,72,61,86,85,215,148,241,542,1068,235,101
25,강동구,2547,332,27,163,49,154,202,273,377,356,614,0

In [351]:
CCTV.rename(columns={CCTV.columns[0]:"지역구"},inplace=True)

In [352]:
CCTV=CCTV.drop(index=0)

In [353]:
CCTV

,지역구,총계,2012년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
1,종로구,1772,813,0,0,210,150,1,261,85,9,200,43
2,중 구,2333,16,114,87,77,236,240,372,386,155,361,289
3,용산구,2383,34,71,234,125,221,298,351,125,307,617,0
4,성동구,3602,448,125,212,105,339,310,874,390,262,461,76
5,광진구,2588,35,57,100,187,98,52,675,465,712,175,32
6,동대문구,2497,1090,146,60,29,111,233,136,197,209,223,63
7,중랑구,3296,302,24,253,88,141,161,162,173,1049,939,4
8,성북구,3958,83,78,170,230,323,594,460,867,714,251,188
9,강북구,2462,0,0,24,65,105,243,6,392,1000,588,39
10,도봉구,1629,39,22,96,181,79,159,134,222,198,168,331
11,노원구,2415,0,97,193,77,516,331,175,216,320,386,104
12,은평구,3791,14,3,44,332,329,555,403,635,1057,288,131
13,서대문구,2940,730,253,155,108,137,223,356,237,343,397,1
14,마포구,2421,58,93,77,61,162,454,359,343,494,300,20
15,양천구,3312,1413,167,181,143,180,350,139,140,274,325,0
16,강서구,2560,55,129,106,213,188,168,506,259,457,356,123
17,구로구,4075,852,216,349,187,268,326,540,488,434,415,0
18,금천구,2374,0,0,178,80,361,133,196,540,369,508,9
19,영등포구,3778,572,136,238,123,209,248,311,658,65,1213,5
20,동작구,2297,41,24,25,503,128,253,271,300,322,419,11
21,관악구,4942,428,205,291,513,529,621,687,663,640,331,34
22,서초구,3704,116,75,94,71,563,516,1060,428,358,420,3
23,강남구,6502,124,77,75,597,840,1310,999,748,789,942,1
24,송파구,2854,72,61,86,85,215,148,241,542,1068,235,101
25,강동구,2547,332,27,163,49,154,202,273,377,356,614,0

In [354]:
# CCTV.set_index('지역구',inplace=True)

In [355]:
CCTV.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25 entries, 1 to 25
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   지역구       25 non-null     object
 1   총계        25 non-null     int64
 2   2012년 이전  25 non-null     int64
 3   2012년     25 non-null     int64
 4   2013년     25 non-null     int64
 5   2014년     25 non-null     int64
 6   2015년     25 non-null     int64
 7   2016년     25 non-null     int64
 8   2017년     25 non-null     int64
 9   2018년     25 non-null     int64
 10  2019년     25 non-null     int64
 11  2020년     25 non-null     int64
 12  2021년     25 non-null     int64
dtypes: int64(12), object(1)
memory usage: 2.7+ KB

In [356]:
# CCTV = CCTV.astype('int')

In [357]:
CCTV.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25 entries, 1 to 25
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   지역구       25 non-null     object
 1   총계        25 non-null     int64
 2   2012년 이전  25 non-null     int64
 3   2012년     25 non-null     int64
 4   2013년     25 non-null     int64
 5   2014년     25 non-null     int64
 6   2015년     25 non-null     int64
 7   2016년     25 non-null     int64
 8   2017년     25 non-null     int64
 9   2018년     25 non-null     int64
 10  2019년     25 non-null     int64
 11  2020년     25 non-null     int64
 12  2021년     25 non-null     int64
dtypes: int64(12), object(1)
memory usage: 2.7+ KB

In [358]:
CCTV['2017']= CCTV['총계'] - CCTV['2021년'] - CCTV['2020년'] - CCTV['2019년'] - CCTV['2018년']
CCTV['2018']= CCTV['총계'] - CCTV['2021년'] - CCTV['2020년'] - CCTV['2019년'] 
CCTV['2019']= CCTV['총계'] - CCTV['2021년'] - CCTV['2020년']

In [359]:
CCTV=CCTV[['지역구','2017','2018','2019']]

In [360]:
CCTV

     지역구  2017  2018  2019
1    종로구  1435  1520  1529
2    중 구  1142  1528  1683
3    용산구  1334  1459  1766
4    성동구  2413  2803  3065
5    광진구  1204  1669  2381
6   동대문구  1805  2002  2211
7    중랑구  1131  1304  2353
8    성북구  1938  2805  3519
9    강북구   443   835  1835
10   도봉구   710   932  1130
11   노원구  1389  1605  1925
12   은평구  1680  2315  3372
13  서대문구  1962  2199  2542
14   마포구  1264  1607  2101
15   양천구  2573  2713  2987
16   강서구  1365  1624  2081
17   구로구  2738  3226  3660
18   금천구   948  1488  1857
19  영등포구  1837  2495  2560
20   동작구  1245  1545  1867
21   관악구  3274  3937  4577
22   서초구  2495  2923  3281
23   강남구  4022  4770  5559
24   송파구   908  1450  2518
25   강동구  1200  1577  1933

In [361]:
CCTV_2017=CCTV[['지역구','2017']]
CCTV_2018=CCTV[['지역구','2018']]
CCTV_2019=CCTV[['지역구','2019']]

In [362]:
CCTV_2017
CCTV_2018
CCTV_2019

     지역구  2017
1    종로구  1435
2    중 구  1142
3    용산구  1334
4    성동구  2413
5    광진구  1204
6   동대문구  1805
7    중랑구  1131
8    성북구  1938
9    강북구   443
10   도봉구   710
11   노원구  1389
12   은평구  1680
13  서대문구  1962
14   마포구  1264
15   양천구  2573
16   강서구  1365
17   구로구  2738
18   금천구   948
19  영등포구  1837
20   동작구  1245
21   관악구  3274
22   서초구  2495
23   강남구  4022
24   송파구   908
25   강동구  1200

     지역구  2018
1    종로구  1520
2    중 구  1528
3    용산구  1459
4    성동구  2803
5    광진구  1669
6   동대문구  2002
7    중랑구  1304
8    성북구  2805
9    강북구   835
10   도봉구   932
11   노원구  1605
12   은평구  2315
13  서대문구  2199
14   마포구  1607
15   양천구  2713
16   강서구  1624
17   구로구  3226
18   금천구  1488
19  영등포구  2495
20   동작구  1545
21   관악구  3937
22   서초구  2923
23   강남구  4770
24   송파구  1450
25   강동구  1577

     지역구  2019
1    종로구  1529
2    중 구  1683
3    용산구  1766
4    성동구  3065
5    광진구  2381
6   동대문구  2211
7    중랑구  2353
8    성북구  3519
9    강북구  1835
10   도봉구  1130
11   노원구  1925
12   은평구  3372
13  서대문구  2542
14   마포구  2101
15   양천구  2987
16   강서구  2081
17   구로구  3660
18   금천구  1857
19  영등포구  2560
20   동작구  1867
21   관악구  4577
22   서초구  3281
23   강남구  5559
24   송파구  2518
25   강동구  1933

In [363]:
def func(x) :
    if x >=0  :
        return 2017
    else :
        return "none"
CCTV_2017["년도"] = CCTV_2017["2017"].apply(lambda x : func(x))

<ipython-input-363-34af38f87775>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  CCTV_2017["년도"] = CCTV_2017["2017"].apply(lambda x : func(x))

In [364]:
CCTV_2017

     지역구  2017    년도
1    종로구  1435  2017
2    중 구  1142  2017
3    용산구  1334  2017
4    성동구  2413  2017
5    광진구  1204  2017
6   동대문구  1805  2017
7    중랑구  1131  2017
8    성북구  1938  2017
9    강북구   443  2017
10   도봉구   710  2017
11   노원구  1389  2017
12   은평구  1680  2017
13  서대문구  1962  2017
14   마포구  1264  2017
15   양천구  2573  2017
16   강서구  1365  2017
17   구로구  2738  2017
18   금천구   948  2017
19  영등포구  1837  2017
20   동작구  1245  2017
21   관악구  3274  2017
22   서초구  2495  2017
23   강남구  4022  2017
24   송파구   908  2017
25   강동구  1200  2017

In [375]:
CCTV_2017.rename(columns = {'2017' : '합계'},inplace = True)
CCTV_2017

     지역구    합계    년도
1    종로구  1435  2017
2    중 구  1142  2017
3    용산구  1334  2017
4    성동구  2413  2017
5    광진구  1204  2017
6   동대문구  1805  2017
7    중랑구  1131  2017
8    성북구  1938  2017
9    강북구   443  2017
10   도봉구   710  2017
11   노원구  1389  2017
12   은평구  1680  2017
13  서대문구  1962  2017
14   마포구  1264  2017
15   양천구  2573  2017
16   강서구  1365  2017
17   구로구  2738  2017
18   금천구   948  2017
19  영등포구  1837  2017
20   동작구  1245  2017
21   관악구  3274  2017
22   서초구  2495  2017
23   강남구  4022  2017
24   송파구   908  2017
25   강동구  1200  2017

In [365]:
def func(x) :
    if x >=0  :
        return 2018
    else :
        return "none"
CCTV_2018["년도"] = CCTV_2018["2018"].apply(lambda x : func(x))

<ipython-input-365-089614cc7fc5>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  CCTV_2018["년도"] = CCTV_2018["2018"].apply(lambda x : func(x))

In [366]:
CCTV_2018

     지역구  2018    년도
1    종로구  1520  2018
2    중 구  1528  2018
3    용산구  1459  2018
4    성동구  2803  2018
5    광진구  1669  2018
6   동대문구  2002  2018
7    중랑구  1304  2018
8    성북구  2805  2018
9    강북구   835  2018
10   도봉구   932  2018
11   노원구  1605  2018
12   은평구  2315  2018
13  서대문구  2199  2018
14   마포구  1607  2018
15   양천구  2713  2018
16   강서구  1624  2018
17   구로구  3226  2018
18   금천구  1488  2018
19  영등포구  2495  2018
20   동작구  1545  2018
21   관악구  3937  2018
22   서초구  2923  2018
23   강남구  4770  2018
24   송파구  1450  2018
25   강동구  1577  2018

In [376]:
CCTV_2018.rename(columns = {'2018' : '합계'},inplace = True)
CCTV_2018

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

     지역구    합계    년도
1    종로구  1520  2018
2    중 구  1528  2018
3    용산구  1459  2018
4    성동구  2803  2018
5    광진구  1669  2018
6   동대문구  2002  2018
7    중랑구  1304  2018
8    성북구  2805  2018
9    강북구   835  2018
10   도봉구   932  2018
11   노원구  1605  2018
12   은평구  2315  2018
13  서대문구  2199  2018
14   마포구  1607  2018
15   양천구  2713  2018
16   강서구  1624  2018
17   구로구  3226  2018
18   금천구  1488  2018
19  영등포구  2495  2018
20   동작구  1545  2018
21   관악구  3937  2018
22   서초구  2923  2018
23   강남구  4770  2018
24   송파구  1450  2018
25   강동구  1577  2018

In [367]:
def func(x) :
    if x >=0  :
        return 2019
    else :
        return "none"
CCTV_2019["년도"] = CCTV_2019["2019"].apply(lambda x : func(x))

<ipython-input-367-fcf6e3b8d4db>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  CCTV_2019["년도"] = CCTV_2019["2019"].apply(lambda x : func(x))

In [368]:
CCTV_2019

     지역구  2019    년도
1    종로구  1529  2019
2    중 구  1683  2019
3    용산구  1766  2019
4    성동구  3065  2019
5    광진구  2381  2019
6   동대문구  2211  2019
7    중랑구  2353  2019
8    성북구  3519  2019
9    강북구  1835  2019
10   도봉구  1130  2019
11   노원구  1925  2019
12   은평구  3372  2019
13  서대문구  2542  2019
14   마포구  2101  2019
15   양천구  2987  2019
16   강서구  2081  2019
17   구로구  3660  2019
18   금천구  1857  2019
19  영등포구  2560  2019
20   동작구  1867  2019
21   관악구  4577  2019
22   서초구  3281  2019
23   강남구  5559  2019
24   송파구  2518  2019
25   강동구  1933  2019

In [377]:
CCTV_2019.rename(columns = {'2019' : '합계'},inplace = True)
CCTV_2019

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

     지역구    합계    년도
1    종로구  1529  2019
2    중 구  1683  2019
3    용산구  1766  2019
4    성동구  3065  2019
5    광진구  2381  2019
6   동대문구  2211  2019
7    중랑구  2353  2019
8    성북구  3519  2019
9    강북구  1835  2019
10   도봉구  1130  2019
11   노원구  1925  2019
12   은평구  3372  2019
13  서대문구  2542  2019
14   마포구  2101  2019
15   양천구  2987  2019
16   강서구  2081  2019
17   구로구  3660  2019
18   금천구  1857  2019
19  영등포구  2560  2019
20   동작구  1867  2019
21   관악구  4577  2019
22   서초구  3281  2019
23   강남구  5559  2019
24   송파구  2518  2019
25   강동구  1933  2019

In [378]:
cctv_total= pd.concat([CCTV_2017,CCTV_2018,CCTV_2019])

In [379]:
cctv_total

    지역구    합계    년도
1   종로구  1435  2017
2   중 구  1142  2017
3   용산구  1334  2017
4   성동구  2413  2017
5   광진구  1204  2017
..  ...   ...   ...
21  관악구  4577  2019
22  서초구  3281  2019
23  강남구  5559  2019
24  송파구  2518  2019
25  강동구  1933  2019

[75 rows x 3 columns]

In [380]:
cctv_total.set_index(['년도','지역구'],inplace=True)

In [381]:
cctv_total

            합계
년도   지역구
2017 종로구  1435
     중 구  1142
     용산구  1334
     성동구  2413
     광진구  1204
...        ...
2019 관악구  4577
     서초구  3281
     강남구  5559
     송파구  2518
     강동구  1933

[75 rows x 1 columns]

In [382]:
cctv_total.to_csv('../[0]data/서울시_CCTV.csv')