In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

import matplotlib.font_manager as fm
font_name = fm.FontProperties(fname="C:/Windows/Fonts/malgun.ttf").get_name()
plt.rc('font', family=font_name)

mpl.rcParams["axes.unicode_minus"] = False

In [2]:
# 전체 코드 출력
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

In [3]:
# 한글 문제
# matplotlit의 기본 폰트에서 한글 지원되지 않기 때문에
# matplotlib의 폰트 변경 필요
import platform

from matplotlib import font_manager, rc
plt.rcParams['axes.unicode_minus'] = False

if platform.system() == 'Darwin':  # 맥OS 
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows':  # 윈도우
    path = "c:/Windows/Fonts/malgun.ttf"
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else:
    print('Unknown system...  sorry~~~')

In [4]:
# 데이터 불러오기 
cctv_seoul=pd.read_csv('../[0]data/서울시_CCTV.csv',index_col=0)

In [5]:
cctv_seoul=cctv_seoul.reset_index()

In [6]:
cctv_seoul=cctv_seoul.set_index(['년도','지역구'])

In [7]:
cctv_seoul2017=cctv_seoul.loc[2017]
cctv_seoul2018=cctv_seoul.loc[2018]
cctv_seoul2019=cctv_seoul.loc[2019]

In [8]:
cctv_seoul2017
cctv_seoul2018
cctv_seoul2019

        합계
지역구
종로구   1435
중 구   1142
용산구   1334
성동구   2413
광진구   1204
동대문구  1805
중랑구   1131
성북구   1938
강북구    443
도봉구    710
노원구   1389
은평구   1680
서대문구  1962
마포구   1264
양천구   2573
강서구   1365
구로구   2738
금천구    948
영등포구  1837
동작구   1245
관악구   3274
서초구   2495
강남구   4022
송파구    908
강동구   1200

        합계
지역구
종로구   1520
중 구   1528
용산구   1459
성동구   2803
광진구   1669
동대문구  2002
중랑구   1304
성북구   2805
강북구    835
도봉구    932
노원구   1605
은평구   2315
서대문구  2199
마포구   1607
양천구   2713
강서구   1624
구로구   3226
금천구   1488
영등포구  2495
동작구   1545
관악구   3937
서초구   2923
강남구   4770
송파구   1450
강동구   1577

        합계
지역구
종로구   1529
중 구   1683
용산구   1766
성동구   3065
광진구   2381
동대문구  2211
중랑구   2353
성북구   3519
강북구   1835
도봉구   1130
노원구   1925
은평구   3372
서대문구  2542
마포구   2101
양천구   2987
강서구   2081
구로구   3660
금천구   1857
영등포구  2560
동작구   1867
관악구   4577
서초구   3281
강남구   5559
송파구   2518
강동구   1933

In [9]:
cctv_seoul1=pd.merge(cctv_seoul2017,cctv_seoul2018,on="지역구")

In [10]:
cctv_seoul=pd.merge(cctv_seoul1,cctv_seoul2019,on="지역구")

In [11]:
cctv_seoul.rename(columns = {'합계_x':'cctv합계(2017)','합계_y':'cctv합계(2018)','합계':'cctv합계(2019)'},inplace = True)

In [12]:
cctv_seoul.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25 entries, 종로구 to 강동구
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   cctv합계(2017)  25 non-null     int64
 1   cctv합계(2018)  25 non-null     int64
 2   cctv합계(2019)  25 non-null     int64
dtypes: int64(3)
memory usage: 800.0+ bytes

In [13]:
cctv_seoul['cctv합계'] = (cctv_seoul['cctv합계(2017)']+cctv_seoul['cctv합계(2018)']+cctv_seoul['cctv합계(2019)']/3).round()

In [14]:
cctv_seoul=cctv_seoul[['cctv합계']]

In [15]:
cctv_seoul

       cctv합계
지역구
종로구    3465.0
중 구    3231.0
용산구    3382.0
성동구    6238.0
광진구    3667.0
동대문구   4544.0
중랑구    3219.0
성북구    5916.0
강북구    1890.0
도봉구    2019.0
노원구    3636.0
은평구    5119.0
서대문구   5008.0
마포구    3571.0
양천구    6282.0
강서구    3683.0
구로구    7184.0
금천구    3055.0
영등포구   5185.0
동작구    3412.0
관악구    8737.0
서초구    6512.0
강남구   10645.0
송파구    3197.0
강동구    3421.0

In [16]:
crime_ranking=pd.read_csv('./5대범죄발생율합계.csv',index_col=0)

In [17]:
crime_ranking

       5대범죄합계
지역구
종로구    9029.0
중구     9656.0
용산구    8575.0
성동구    6061.0
광진구    9898.0
동대문구   8886.0
중랑구   10282.0
성북구    7435.0
강북구    8109.0
도봉구    4951.0
노원구    9600.0
은평구    8766.0
서대문구   6896.0
마포구   12064.0
양천구    8468.0
강서구   11405.0
구로구   11274.0
금천구    7593.0
영등포구  13749.0
동작구    7563.0
관악구   12327.0
서초구   11281.0
강남구   17668.0
송파구   13282.0
강동구    9518.0

In [18]:
crime_ranking.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25 entries, 종로구 to 강동구
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   5대범죄합계  25 non-null     float64
dtypes: float64(1)
memory usage: 400.0+ bytes

In [19]:
len(crime_ranking)

25

In [20]:
cctv_seoul=cctv_seoul.reset_index()

In [21]:
cctv_seoul['지역구'][(cctv_seoul['지역구'] == '중 구')] = '중구'

<ipython-input-21-a02c50619b6f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cctv_seoul['지역구'][(cctv_seoul['지역구'] == '중 구')] = '중구'

In [22]:
# cctv_seoul=cctv_seoul.replace()

In [23]:
cctv_seoul

     지역구   cctv합계
0    종로구   3465.0
1     중구   3231.0
2    용산구   3382.0
3    성동구   6238.0
4    광진구   3667.0
5   동대문구   4544.0
6    중랑구   3219.0
7    성북구   5916.0
8    강북구   1890.0
9    도봉구   2019.0
10   노원구   3636.0
11   은평구   5119.0
12  서대문구   5008.0
13   마포구   3571.0
14   양천구   6282.0
15   강서구   3683.0
16   구로구   7184.0
17   금천구   3055.0
18  영등포구   5185.0
19   동작구   3412.0
20   관악구   8737.0
21   서초구   6512.0
22   강남구  10645.0
23   송파구   3197.0
24   강동구   3421.0

In [24]:
cctv_seoul=cctv_seoul.set_index(['지역구'])

In [25]:
cctv_crime=pd.merge(crime_ranking,cctv_seoul,on="지역구")

In [26]:
cctv_crime

       5대범죄합계   cctv합계
지역구
종로구    9029.0   3465.0
중구     9656.0   3231.0
용산구    8575.0   3382.0
성동구    6061.0   6238.0
광진구    9898.0   3667.0
동대문구   8886.0   4544.0
중랑구   10282.0   3219.0
성북구    7435.0   5916.0
강북구    8109.0   1890.0
도봉구    4951.0   2019.0
노원구    9600.0   3636.0
은평구    8766.0   5119.0
서대문구   6896.0   5008.0
마포구   12064.0   3571.0
양천구    8468.0   6282.0
강서구   11405.0   3683.0
구로구   11274.0   7184.0
금천구    7593.0   3055.0
영등포구  13749.0   5185.0
동작구    7563.0   3412.0
관악구   12327.0   8737.0
서초구   11281.0   6512.0
강남구   17668.0  10645.0
송파구   13282.0   3197.0
강동구    9518.0   3421.0

In [27]:
len(cctv_crime)

25

In [28]:
cctv_crime.to_csv('cctv_범죄(준영오빠).csv')

In [29]:
cctv_crime['5대범죄발생대비cctv개수'] = ((cctv_crime['5대범죄합계']/cctv_seoul['cctv합계'])*100)

In [30]:
cctv_crime =cctv_crime.sort_values(by='5대범죄발생대비cctv개수',ascending=False)

In [31]:
cctv_crime=cctv_crime.round()

In [32]:
cctv_crime['순위']=cctv_crime['5대범죄발생대비cctv개수'].rank(ascending=False)

In [33]:
cctv_crime

       5대범죄합계   cctv합계  5대범죄발생대비cctv개수    순위
지역구
강북구    8109.0   1890.0           429.0   1.0
송파구   13282.0   3197.0           415.0   2.0
마포구   12064.0   3571.0           338.0   3.0
중랑구   10282.0   3219.0           319.0   4.0
강서구   11405.0   3683.0           310.0   5.0
중구     9656.0   3231.0           299.0   6.0
강동구    9518.0   3421.0           278.0   7.0
광진구    9898.0   3667.0           270.0   8.0
영등포구  13749.0   5185.0           265.0   9.0
노원구    9600.0   3636.0           264.0  10.0
종로구    9029.0   3465.0           261.0  11.0
용산구    8575.0   3382.0           254.0  12.0
금천구    7593.0   3055.0           249.0  13.0
도봉구    4951.0   2019.0           245.0  14.0
동작구    7563.0   3412.0           222.0  15.0
동대문구   8886.0   4544.0           196.0  16.0
서초구   11281.0   6512.0           173.0  17.0
은평구    8766.0   5119.0           171.0  18.0
강남구   17668.0  10645.0           166.0  19.0
구로구   11274.0   7184.0           157.0  20.0
관악구   12327.0   8737.0           141.0  21.0
서대문구   6896.0   5008.0           138.0  22.0
양천구    8468.0   6282.0           135.0  23.0
성북구    7435.0   5916.0           126.0  24.0
성동구    6061.0   6238.0            97.0  25.0

In [34]:
cctv_crime=cctv_crime.astype(int)

In [35]:
len(cctv_crime)

25

In [36]:
cctv_crime.to_csv('cctv_랭킹.csv')